services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

  surveillance.alert.api:
    image: ${DOCKER_REGISTRY-}surveillancealertapi
    build:
      context: .
      dockerfile: Services/Alert/Surveillance.Alert.Api/Dockerfile

  surveillance.identity.api:
    image: ${DOCKER_REGISTRY-}surveillanceidentityapi
    build:
      context: .
      dockerfile: Services/Identity/Surveillance.Identity.Api/Dockerfile

  surveillance.notification.api:
    image: ${DOCKER_REGISTRY-}surveillancenotificationapi
    build:
      context: .
      dockerfile: Services/Notification/Surveillance.Notification.Api/Dockerfile
